// AUTO-GENERATED by scripts/generate-map-data.mjs — do not edit by hand.
// Source: jDip standard map data (GPL) via github.com/diplomacy/diplomacy.
// Codes are dpjudge province codes; fleet locations may carry a coast
// qualifier ("stp/sc"). ARMY_ADJ/FLEET_ADJ are the complete standard
// Diplomacy adjacency tables.

export type ProvinceType = "land" | "coast" | "water";
export interface ProvinceInfo {
  name: string;
  type: ProvinceType;
  sc: boolean;
  svgId: string;
  unit: { x: number; y: number };
  scPos?: { x: number; y: number };
  coasts?: string[];
}

export const PROVINCES: Record<string, ProvinceInfo> = {
 "adr": {
  "name": "Mer Adriatique",
  "type": "water",
  "sc": false,
  "svgId": "_adr",
  "unit": {
   "x": 793.5,
   "y": 1048
  }
 },
 "aeg": {
  "name": "Mer Égée",
  "type": "water",
  "sc": false,
  "svgId": "_aeg",
  "unit": {
   "x": 1043.5,
   "y": 1230
  }
 },
 "alb": {
  "name": "Albanie",
  "type": "coast",
  "sc": false,
  "svgId": "_alb",
  "unit": {
   "x": 906.5,
   "y": 1113
  }
 },
 "ank": {
  "name": "Ankara",
  "type": "coast",
  "sc": true,
  "svgId": "_ank",
  "unit": {
   "x": 1301.5,
   "y": 1110
  },
  "scPos": {
   "x": 1272.5,
   "y": 1143
  }
 },
 "apu": {
  "name": "Apulie",
  "type": "coast",
  "sc": false,
  "svgId": "_apu",
  "unit": {
   "x": 791.5,
   "y": 1106
  }
 },
 "arm": {
  "name": "Arménie",
  "type": "coast",
  "sc": false,
  "svgId": "_arm",
  "unit": {
   "x": 1484.5,
   "y": 1090
  }
 },
 "bal": {
  "name": "Mer Baltique",
  "type": "water",
  "sc": false,
  "svgId": "_bal",
  "unit": {
   "x": 878.5,
   "y": 610
  }
 },
 "bar": {
  "name": "Mer de Barents",
  "type": "water",
  "sc": false,
  "svgId": "_bar",
  "unit": {
   "x": 1162.5,
   "y": 73
  }
 },
 "bel": {
  "name": "Belgique",
  "type": "coast",
  "sc": true,
  "svgId": "_bel",
  "unit": {
   "x": 561.5,
   "y": 753
  },
  "scPos": {
   "x": 576.5,
   "y": 754
  }
 },
 "ber": {
  "name": "Berlin",
  "type": "coast",
  "sc": true,
  "svgId": "_ber",
  "unit": {
   "x": 771.5,
   "y": 690
  },
  "scPos": {
   "x": 784.5,
   "y": 735
  }
 },
 "bla": {
  "name": "Mer Noire",
  "type": "water",
  "sc": false,
  "svgId": "_bla",
  "unit": {
   "x": 1233.5,
   "y": 1000
  }
 },
 "boh": {
  "name": "Bohême",
  "type": "land",
  "sc": false,
  "svgId": "_boh",
  "unit": {
   "x": 806.5,
   "y": 814
  }
 },
 "bot": {
  "name": "Golfe de Botnie",
  "type": "water",
  "sc": false,
  "svgId": "_bot",
  "unit": {
   "x": 941.5,
   "y": 485
  }
 },
 "bre": {
  "name": "Brest",
  "type": "coast",
  "sc": true,
  "svgId": "_bre",
  "unit": {
   "x": 404.5,
   "y": 819
  },
  "scPos": {
   "x": 370.5,
   "y": 798
  }
 },
 "bud": {
  "name": "Budapest",
  "type": "land",
  "sc": true,
  "svgId": "_bud",
  "unit": {
   "x": 950.5,
   "y": 904
  },
  "scPos": {
   "x": 901.5,
   "y": 915
  }
 },
 "bul": {
  "name": "Bulgarie",
  "type": "coast",
  "sc": true,
  "svgId": "_bul",
  "unit": {
   "x": 1048.5,
   "y": 1068
  },
  "scPos": {
   "x": 1014.5,
   "y": 1077
  },
  "coasts": [
   "ec",
   "sc"
  ]
 },
 "bur": {
  "name": "Bourgogne",
  "type": "land",
  "sc": false,
  "svgId": "_bur",
  "unit": {
   "x": 559.5,
   "y": 871
  }
 },
 "cly": {
  "name": "Clyde",
  "type": "coast",
  "sc": false,
  "svgId": "_cly",
  "unit": {
   "x": 436.5,
   "y": 492
  }
 },
 "con": {
  "name": "Constantinople",
  "type": "coast",
  "sc": true,
  "svgId": "_con",
  "unit": {
   "x": 1145.5,
   "y": 1137
  },
  "scPos": {
   "x": 1142.5,
   "y": 1118
  }
 },
 "den": {
  "name": "Danemark",
  "type": "coast",
  "sc": true,
  "svgId": "_den",
  "unit": {
   "x": 703.5,
   "y": 587
  },
  "scPos": {
   "x": 768.5,
   "y": 625
  }
 },
 "eas": {
  "name": "Méditerranée orientale",
  "type": "water",
  "sc": false,
  "svgId": "_eas",
  "unit": {
   "x": 1218.5,
   "y": 1311
  }
 },
 "edi": {
  "name": "Édimbourg",
  "type": "coast",
  "sc": true,
  "svgId": "_edi",
  "unit": {
   "x": 473.5,
   "y": 514
  },
  "scPos": {
   "x": 490.5,
   "y": 564
  }
 },
 "eng": {
  "name": "Manche",
  "type": "water",
  "sc": false,
  "svgId": "_eng",
  "unit": {
   "x": 394.5,
   "y": 751
  }
 },
 "fin": {
  "name": "Finlande",
  "type": "coast",
  "sc": false,
  "svgId": "_fin",
  "unit": {
   "x": 988.5,
   "y": 380
  }
 },
 "gal": {
  "name": "Galicie",
  "type": "land",
  "sc": false,
  "svgId": "_gal",
  "unit": {
   "x": 999.5,
   "y": 831
  }
 },
 "gas": {
  "name": "Gascogne",
  "type": "coast",
  "sc": false,
  "svgId": "_gas",
  "unit": {
   "x": 422.5,
   "y": 912
  }
 },
 "gre": {
  "name": "Grèce",
  "type": "coast",
  "sc": true,
  "svgId": "_gre",
  "unit": {
   "x": 966.5,
   "y": 1190
  },
  "scPos": {
   "x": 1024.5,
   "y": 1236
  }
 },
 "hel": {
  "name": "Baie d'Heligoland",
  "type": "water",
  "sc": false,
  "svgId": "_hel",
  "unit": {
   "x": 651.5,
   "y": 631
  }
 },
 "hol": {
  "name": "Hollande",
  "type": "coast",
  "sc": true,
  "svgId": "_hol",
  "unit": {
   "x": 596.5,
   "y": 711
  },
  "scPos": {
   "x": 631.5,
   "y": 691
  }
 },
 "ion": {
  "name": "Mer Ionienne",
  "type": "water",
  "sc": false,
  "svgId": "_ion",
  "unit": {
   "x": 846.5,
   "y": 1286
  }
 },
 "iri": {
  "name": "Mer d'Irlande",
  "type": "water",
  "sc": false,
  "svgId": "_iri",
  "unit": {
   "x": 335.5,
   "y": 661
  }
 },
 "kie": {
  "name": "Kiel",
  "type": "coast",
  "sc": true,
  "svgId": "_kie",
  "unit": {
   "x": 683.5,
   "y": 701
  },
  "scPos": {
   "x": 725.5,
   "y": 684
  }
 },
 "lon": {
  "name": "Londres",
  "type": "coast",
  "sc": true,
  "svgId": "_lon",
  "unit": {
   "x": 488.5,
   "y": 675
  },
  "scPos": {
   "x": 490.5,
   "y": 716
  }
 },
 "lvn": {
  "name": "Livonie",
  "type": "coast",
  "sc": false,
  "svgId": "_lvn",
  "unit": {
   "x": 1025.5,
   "y": 567
  }
 },
 "lvp": {
  "name": "Liverpool",
  "type": "coast",
  "sc": true,
  "svgId": "_lvp",
  "unit": {
   "x": 450.5,
   "y": 576
  },
  "scPos": {
   "x": 459.5,
   "y": 637
  }
 },
 "lyo": {
  "name": "Golfe du Lion",
  "type": "water",
  "sc": false,
  "svgId": "_gol",
  "unit": {
   "x": 514.3,
   "y": 1055
  }
 },
 "mao": {
  "name": "Atlantique central",
  "type": "water",
  "sc": false,
  "svgId": "_mid",
  "unit": {
   "x": 141.8,
   "y": 835.3
  }
 },
 "mar": {
  "name": "Marseille",
  "type": "coast",
  "sc": true,
  "svgId": "_mar",
  "unit": {
   "x": 524.5,
   "y": 975
  },
  "scPos": {
   "x": 563.5,
   "y": 1017
  }
 },
 "mos": {
  "name": "Moscou",
  "type": "land",
  "sc": true,
  "svgId": "_mos",
  "unit": {
   "x": 1200.5,
   "y": 590
  },
  "scPos": {
   "x": 1268.5,
   "y": 583
  }
 },
 "mun": {
  "name": "Munich",
  "type": "land",
  "sc": true,
  "svgId": "_mun",
  "unit": {
   "x": 693.5,
   "y": 828
  },
  "scPos": {
   "x": 731.5,
   "y": 877
  }
 },
 "naf": {
  "name": "Afrique du Nord",
  "type": "coast",
  "sc": false,
  "svgId": "_naf",
  "unit": {
   "x": 325.5,
   "y": 1281
  }
 },
 "nao": {
  "name": "Atlantique Nord",
  "type": "water",
  "sc": false,
  "svgId": "_nat",
  "unit": {
   "x": 180.1,
   "y": 288.2
  }
 },
 "nap": {
  "name": "Naples",
  "type": "coast",
  "sc": true,
  "svgId": "_nap",
  "unit": {
   "x": 806.5,
   "y": 1170
  },
  "scPos": {
   "x": 779.5,
   "y": 1142
  }
 },
 "nth": {
  "name": "Mer du Nord",
  "type": "water",
  "sc": false,
  "svgId": "_nth",
  "unit": {
   "x": 553.5,
   "y": 560
  }
 },
 "nwg": {
  "name": "Mer de Norvège",
  "type": "water",
  "sc": false,
  "svgId": "_nrg",
  "unit": {
   "x": 652.7,
   "y": 181.8
  }
 },
 "nwy": {
  "name": "Norvège",
  "type": "coast",
  "sc": true,
  "svgId": "_nwy",
  "unit": {
   "x": 703.5,
   "y": 410
  },
  "scPos": {
   "x": 762.5,
   "y": 462
  }
 },
 "par": {
  "name": "Paris",
  "type": "land",
  "sc": true,
  "svgId": "_par",
  "unit": {
   "x": 488.5,
   "y": 845
  },
  "scPos": {
   "x": 519.5,
   "y": 818
  }
 },
 "pic": {
  "name": "Picardie",
  "type": "coast",
  "sc": false,
  "svgId": "_pic",
  "unit": {
   "x": 523.5,
   "y": 781
  }
 },
 "pie": {
  "name": "Piémont",
  "type": "coast",
  "sc": false,
  "svgId": "_pie",
  "unit": {
   "x": 630.5,
   "y": 968
  }
 },
 "por": {
  "name": "Portugal",
  "type": "coast",
  "sc": true,
  "svgId": "_por",
  "unit": {
   "x": 181.5,
   "y": 1013
  },
  "scPos": {
   "x": 152.5,
   "y": 1059
  }
 },
 "pru": {
  "name": "Prusse",
  "type": "coast",
  "sc": false,
  "svgId": "_pru",
  "unit": {
   "x": 865.5,
   "y": 690
  }
 },
 "rom": {
  "name": "Rome",
  "type": "coast",
  "sc": true,
  "svgId": "_rom",
  "unit": {
   "x": 731.5,
   "y": 1102
  },
  "scPos": {
   "x": 720.5,
   "y": 1086
  }
 },
 "ruh": {
  "name": "Ruhr",
  "type": "land",
  "sc": false,
  "svgId": "_ruh",
  "unit": {
   "x": 636.5,
   "y": 779
  }
 },
 "rum": {
  "name": "Roumanie",
  "type": "coast",
  "sc": true,
  "svgId": "_rum",
  "unit": {
   "x": 1096.5,
   "y": 967
  },
  "scPos": {
   "x": 1084.5,
   "y": 1013
  }
 },
 "ser": {
  "name": "Serbie",
  "type": "land",
  "sc": true,
  "svgId": "_ser",
  "unit": {
   "x": 933.5,
   "y": 1050
  },
  "scPos": {
   "x": 937.5,
   "y": 1020
  }
 },
 "sev": {
  "name": "Sébastopol",
  "type": "coast",
  "sc": true,
  "svgId": "_sev",
  "unit": {
   "x": 1284.5,
   "y": 845
  },
  "scPos": {
   "x": 1268.5,
   "y": 972
  }
 },
 "sil": {
  "name": "Silésie",
  "type": "land",
  "sc": false,
  "svgId": "_sil",
  "unit": {
   "x": 832.5,
   "y": 769
  }
 },
 "ska": {
  "name": "Skagerrak",
  "type": "water",
  "sc": false,
  "svgId": "_ska",
  "unit": {
   "x": 735.5,
   "y": 518
  }
 },
 "smy": {
  "name": "Smyrne",
  "type": "coast",
  "sc": true,
  "svgId": "_smy",
  "unit": {
   "x": 1253.5,
   "y": 1210
  },
  "scPos": {
   "x": 1133.5,
   "y": 1221
  }
 },
 "spa": {
  "name": "Espagne",
  "type": "coast",
  "sc": true,
  "svgId": "_spa",
  "unit": {
   "x": 335.5,
   "y": 1039
  },
  "scPos": {
   "x": 303.5,
   "y": 1055
  },
  "coasts": [
   "nc",
   "sc"
  ]
 },
 "stp": {
  "name": "Saint-Pétersbourg",
  "type": "coast",
  "sc": true,
  "svgId": "_stp",
  "unit": {
   "x": 1166.5,
   "y": 405
  },
  "scPos": {
   "x": 1114.5,
   "y": 468
  },
  "coasts": [
   "nc",
   "sc"
  ]
 },
 "swe": {
  "name": "Suède",
  "type": "coast",
  "sc": true,
  "svgId": "_swe",
  "unit": {
   "x": 829.5,
   "y": 459
  },
  "scPos": {
   "x": 891.5,
   "y": 488
  }
 },
 "syr": {
  "name": "Syrie",
  "type": "coast",
  "sc": false,
  "svgId": "_syr",
  "unit": {
   "x": 1452.5,
   "y": 1206
  }
 },
 "tri": {
  "name": "Trieste",
  "type": "coast",
  "sc": true,
  "svgId": "_tri",
  "unit": {
   "x": 825.5,
   "y": 996
  },
  "scPos": {
   "x": 795.5,
   "y": 974
  }
 },
 "tun": {
  "name": "Tunis",
  "type": "coast",
  "sc": true,
  "svgId": "_tun",
  "unit": {
   "x": 622.5,
   "y": 1300
  },
  "scPos": {
   "x": 648.5,
   "y": 1281
  }
 },
 "tus": {
  "name": "Toscane",
  "type": "coast",
  "sc": false,
  "svgId": "_tus",
  "unit": {
   "x": 686.5,
   "y": 1034
  }
 },
 "tyr": {
  "name": "Tyrol",
  "type": "land",
  "sc": false,
  "svgId": "_tyr",
  "unit": {
   "x": 742.5,
   "y": 904
  }
 },
 "tys": {
  "name": "Mer Tyrrhénienne",
  "type": "water",
  "sc": false,
  "svgId": "_tyn",
  "unit": {
   "x": 698.5,
   "y": 1149.1
  }
 },
 "ukr": {
  "name": "Ukraine",
  "type": "land",
  "sc": false,
  "svgId": "_ukr",
  "unit": {
   "x": 1124.5,
   "y": 800
  }
 },
 "ven": {
  "name": "Venise",
  "type": "coast",
  "sc": true,
  "svgId": "_ven",
  "unit": {
   "x": 707.5,
   "y": 994
  },
  "scPos": {
   "x": 734.5,
   "y": 970
  }
 },
 "vie": {
  "name": "Vienne",
  "type": "land",
  "sc": true,
  "svgId": "_vie",
  "unit": {
   "x": 855.5,
   "y": 864
  },
  "scPos": {
   "x": 836.5,
   "y": 886
  }
 },
 "wal": {
  "name": "Pays de Galles",
  "type": "coast",
  "sc": false,
  "svgId": "_wal",
  "unit": {
   "x": 428.5,
   "y": 658
  }
 },
 "war": {
  "name": "Varsovie",
  "type": "land",
  "sc": true,
  "svgId": "_war",
  "unit": {
   "x": 983.5,
   "y": 740
  },
  "scPos": {
   "x": 938.5,
   "y": 747
  }
 },
 "wes": {
  "name": "Méditerranée occidentale",
  "type": "water",
  "sc": false,
  "svgId": "_wes",
  "unit": {
   "x": 462.5,
   "y": 1163
  }
 },
 "yor": {
  "name": "Yorkshire",
  "type": "coast",
  "sc": false,
  "svgId": "_yor",
  "unit": {
   "x": 492.5,
   "y": 616
  }
 }
};

export const ARMY_ADJ: Record<string, string[]> = {
 "alb": [
  "gre",
  "ser",
  "tri"
 ],
 "ank": [
  "arm",
  "con",
  "smy"
 ],
 "apu": [
  "nap",
  "rom",
  "ven"
 ],
 "arm": [
  "ank",
  "sev",
  "smy",
  "syr"
 ],
 "bel": [
  "bur",
  "hol",
  "pic",
  "ruh"
 ],
 "ber": [
  "kie",
  "mun",
  "pru",
  "sil"
 ],
 "boh": [
  "gal",
  "mun",
  "sil",
  "tyr",
  "vie"
 ],
 "bre": [
  "gas",
  "par",
  "pic"
 ],
 "bud": [
  "gal",
  "rum",
  "ser",
  "tri",
  "vie"
 ],
 "bul": [
  "con",
  "gre",
  "rum",
  "ser"
 ],
 "bur": [
  "bel",
  "gas",
  "mar",
  "mun",
  "par",
  "pic",
  "ruh"
 ],
 "cly": [
  "edi",
  "lvp"
 ],
 "con": [
  "ank",
  "bul",
  "smy"
 ],
 "den": [
  "kie",
  "swe"
 ],
 "edi": [
  "cly",
  "lvp",
  "yor"
 ],
 "fin": [
  "nwy",
  "stp",
  "swe"
 ],
 "gal": [
  "boh",
  "bud",
  "rum",
  "sil",
  "ukr",
  "vie",
  "war"
 ],
 "gas": [
  "bre",
  "bur",
  "mar",
  "par",
  "spa"
 ],
 "gre": [
  "alb",
  "bul",
  "ser"
 ],
 "hol": [
  "bel",
  "kie",
  "ruh"
 ],
 "kie": [
  "ber",
  "den",
  "hol",
  "mun",
  "ruh"
 ],
 "lon": [
  "wal",
  "yor"
 ],
 "lvn": [
  "mos",
  "pru",
  "stp",
  "war"
 ],
 "lvp": [
  "cly",
  "edi",
  "wal",
  "yor"
 ],
 "mar": [
  "bur",
  "gas",
  "pie",
  "spa"
 ],
 "mos": [
  "lvn",
  "sev",
  "stp",
  "ukr",
  "war"
 ],
 "mun": [
  "ber",
  "boh",
  "bur",
  "kie",
  "ruh",
  "sil",
  "tyr"
 ],
 "naf": [
  "tun"
 ],
 "nap": [
  "apu",
  "rom"
 ],
 "nwy": [
  "fin",
  "stp",
  "swe"
 ],
 "par": [
  "bre",
  "bur",
  "gas",
  "pic"
 ],
 "pic": [
  "bel",
  "bre",
  "bur",
  "par"
 ],
 "pie": [
  "mar",
  "tus",
  "tyr",
  "ven"
 ],
 "por": [
  "spa"
 ],
 "pru": [
  "ber",
  "lvn",
  "sil",
  "war"
 ],
 "rom": [
  "apu",
  "nap",
  "tus",
  "ven"
 ],
 "ruh": [
  "bel",
  "bur",
  "hol",
  "kie",
  "mun"
 ],
 "rum": [
  "bud",
  "bul",
  "gal",
  "ser",
  "sev",
  "ukr"
 ],
 "ser": [
  "alb",
  "bud",
  "bul",
  "gre",
  "rum",
  "tri"
 ],
 "sev": [
  "arm",
  "mos",
  "rum",
  "ukr"
 ],
 "sil": [
  "ber",
  "boh",
  "gal",
  "mun",
  "pru",
  "war"
 ],
 "smy": [
  "ank",
  "arm",
  "con",
  "syr"
 ],
 "spa": [
  "gas",
  "mar",
  "por"
 ],
 "stp": [
  "fin",
  "lvn",
  "mos",
  "nwy"
 ],
 "swe": [
  "den",
  "fin",
  "nwy"
 ],
 "syr": [
  "arm",
  "smy"
 ],
 "tri": [
  "alb",
  "bud",
  "ser",
  "tyr",
  "ven",
  "vie"
 ],
 "tun": [
  "naf"
 ],
 "tus": [
  "pie",
  "rom",
  "ven"
 ],
 "tyr": [
  "boh",
  "mun",
  "pie",
  "tri",
  "ven",
  "vie"
 ],
 "ukr": [
  "gal",
  "mos",
  "rum",
  "sev",
  "war"
 ],
 "ven": [
  "apu",
  "pie",
  "rom",
  "tri",
  "tus",
  "tyr"
 ],
 "vie": [
  "boh",
  "bud",
  "gal",
  "tri",
  "tyr"
 ],
 "wal": [
  "lon",
  "lvp",
  "yor"
 ],
 "war": [
  "gal",
  "lvn",
  "mos",
  "pru",
  "sil",
  "ukr"
 ],
 "yor": [
  "edi",
  "lon",
  "lvp",
  "wal"
 ]
};

export const FLEET_ADJ: Record<string, string[]> = {
 "adr": [
  "alb",
  "apu",
  "ion",
  "tri",
  "ven"
 ],
 "aeg": [
  "bul/sc",
  "con",
  "eas",
  "gre",
  "ion",
  "smy"
 ],
 "alb": [
  "adr",
  "gre",
  "ion",
  "tri"
 ],
 "ank": [
  "arm",
  "bla",
  "con"
 ],
 "apu": [
  "adr",
  "ion",
  "nap",
  "ven"
 ],
 "arm": [
  "ank",
  "bla",
  "sev"
 ],
 "bal": [
  "ber",
  "bot",
  "den",
  "kie",
  "lvn",
  "pru",
  "swe"
 ],
 "bar": [
  "nwg",
  "nwy",
  "stp/nc"
 ],
 "bel": [
  "eng",
  "hol",
  "nth",
  "pic"
 ],
 "ber": [
  "bal",
  "kie",
  "pru"
 ],
 "bla": [
  "ank",
  "arm",
  "bul/ec",
  "con",
  "rum",
  "sev"
 ],
 "bot": [
  "bal",
  "fin",
  "lvn",
  "stp/sc",
  "swe"
 ],
 "bre": [
  "eng",
  "gas",
  "mao",
  "pic"
 ],
 "bul/ec": [
  "bla",
  "con",
  "rum"
 ],
 "bul/sc": [
  "aeg",
  "con",
  "gre"
 ],
 "cly": [
  "edi",
  "lvp",
  "nao",
  "nwg"
 ],
 "con": [
  "aeg",
  "ank",
  "bla",
  "bul/ec",
  "bul/sc",
  "smy"
 ],
 "den": [
  "bal",
  "hel",
  "kie",
  "nth",
  "ska",
  "swe"
 ],
 "eas": [
  "aeg",
  "ion",
  "smy",
  "syr"
 ],
 "edi": [
  "cly",
  "nth",
  "nwg",
  "yor"
 ],
 "eng": [
  "bel",
  "bre",
  "iri",
  "lon",
  "mao",
  "nth",
  "pic",
  "wal"
 ],
 "fin": [
  "bot",
  "stp/sc",
  "swe"
 ],
 "gas": [
  "bre",
  "mao",
  "spa/nc"
 ],
 "gre": [
  "aeg",
  "alb",
  "bul/sc",
  "ion"
 ],
 "hel": [
  "den",
  "hol",
  "kie",
  "nth"
 ],
 "hol": [
  "bel",
  "hel",
  "kie",
  "nth"
 ],
 "ion": [
  "adr",
  "aeg",
  "alb",
  "apu",
  "eas",
  "gre",
  "nap",
  "tun",
  "tys"
 ],
 "iri": [
  "eng",
  "lvp",
  "mao",
  "nao",
  "wal"
 ],
 "kie": [
  "bal",
  "ber",
  "den",
  "hel",
  "hol"
 ],
 "lon": [
  "eng",
  "nth",
  "wal",
  "yor"
 ],
 "lvn": [
  "bal",
  "bot",
  "pru",
  "stp/sc"
 ],
 "lvp": [
  "cly",
  "iri",
  "nao",
  "wal"
 ],
 "lyo": [
  "mar",
  "pie",
  "spa/sc",
  "tus",
  "tys",
  "wes"
 ],
 "mao": [
  "bre",
  "eng",
  "gas",
  "iri",
  "naf",
  "nao",
  "por",
  "spa/nc",
  "spa/sc",
  "wes"
 ],
 "mar": [
  "lyo",
  "pie",
  "spa/sc"
 ],
 "naf": [
  "mao",
  "tun",
  "wes"
 ],
 "nao": [
  "cly",
  "iri",
  "lvp",
  "mao",
  "nwg"
 ],
 "nap": [
  "apu",
  "ion",
  "rom",
  "tys"
 ],
 "nwy": [
  "bar",
  "nth",
  "nwg",
  "ska",
  "stp/nc",
  "swe"
 ],
 "nth": [
  "bel",
  "den",
  "edi",
  "eng",
  "hel",
  "hol",
  "lon",
  "nwg",
  "nwy",
  "ska",
  "yor"
 ],
 "nwg": [
  "bar",
  "cly",
  "edi",
  "nao",
  "nth",
  "nwy"
 ],
 "pic": [
  "bel",
  "bre",
  "eng"
 ],
 "pie": [
  "lyo",
  "mar",
  "tus"
 ],
 "por": [
  "mao",
  "spa/nc",
  "spa/sc"
 ],
 "pru": [
  "bal",
  "ber",
  "lvn"
 ],
 "rom": [
  "nap",
  "tus",
  "tys"
 ],
 "rum": [
  "bla",
  "bul/ec",
  "sev"
 ],
 "sev": [
  "arm",
  "bla",
  "rum"
 ],
 "ska": [
  "den",
  "nth",
  "nwy",
  "swe"
 ],
 "smy": [
  "aeg",
  "con",
  "eas",
  "syr"
 ],
 "spa/nc": [
  "gas",
  "mao",
  "por"
 ],
 "spa/sc": [
  "lyo",
  "mao",
  "mar",
  "por",
  "wes"
 ],
 "stp/nc": [
  "bar",
  "nwy"
 ],
 "stp/sc": [
  "bot",
  "fin",
  "lvn"
 ],
 "swe": [
  "bal",
  "bot",
  "den",
  "fin",
  "nwy",
  "ska"
 ],
 "syr": [
  "eas",
  "smy"
 ],
 "tri": [
  "adr",
  "alb",
  "ven"
 ],
 "tun": [
  "ion",
  "naf",
  "tys",
  "wes"
 ],
 "tus": [
  "lyo",
  "pie",
  "rom",
  "tys"
 ],
 "tys": [
  "ion",
  "lyo",
  "nap",
  "rom",
  "tun",
  "tus",
  "wes"
 ],
 "ven": [
  "adr",
  "apu",
  "tri"
 ],
 "wal": [
  "eng",
  "iri",
  "lon",
  "lvp"
 ],
 "wes": [
  "lyo",
  "mao",
  "naf",
  "spa/sc",
  "tun",
  "tys"
 ],
 "yor": [
  "edi",
  "lon",
  "nth"
 ]
};

// Unit anchor points for fleets on a specific coast of a split-coast province
export const COAST_UNIT_POS: Record<string, { x: number; y: number }> = {
 "bul/ec": {
  "x": 1127,
  "y": 1067
 },
 "bul/sc": {
  "x": 1070,
  "y": 1140
 },
 "spa/nc": {
  "x": 289,
  "y": 965
 },
 "spa/sc": {
  "x": 291,
  "y": 1166
 },
 "stp/nc": {
  "x": 1218,
  "y": 222
 },
 "stp/sc": {
  "x": 1066,
  "y": 487
 }
};
